#this will compile all the file
# need to read the instruction of computing the code in file phf.c


CC=gcc
CFLAGS=-Wall -Wextra


all: compile
	
compile: 
	$(CC) $(CFLAGS) hfg.c -o test

clean:
	rm -rf *o compile
